Create Profile with personal stats for authorized users
Eug-VS/chrono-cube pull request #27
Opened 2020-01-05 23:59 UTC by asketonim

2020-01-06 16:38 UTC, eug-vs requested changes

2020-01-06 16:38 UTC, Eug-VS commented on src/components/Profile/Profile.js
> +  const [userName, setUserName] = useState('');
Please rename `userName` -> `username`.

2020-01-06 16:38 UTC, Eug-VS commented on src/components/Profile/Profile.js
> +  const [userSolutions, setUserSolutions] = useState([]);
Let's change it to `profileSolutions`. Just in case if in future we pass this somewhere, we know exactly where it comes from.

2020-01-06 16:38 UTC, Eug-VS commented on src/components/Profile/Profile.js
> +      get('solutions/')
We have specific API URL for this case: `get('solutions/?author=${userId}')` (use proper quotes here, I don't know how to escape them in markdown).

2020-01-06 16:38 UTC, Eug-VS commented on src/components/Scoreboard/Scoreboard.js
> +    const response = await get('scoreboard/');
This file is out of scope of this task. You may change it locally, but do not commit this changes to this branch. In order to fix this, use `git commit --amend` and then force-push (`-f`) your branch.

2020-01-06 16:38 UTC, Eug-VS commented on src/index.js
> +  const [userId, setUserId] = useState(0);
Let's store user object in this state: `[user, setUser] = useState({ username: 'anonymous', id: null  });`
Thus we can pass all user information at once to lower components.

2020-01-06 16:38 UTC, Eug-VS commented on src/components/Profile/Profile.js
> +    if (userId && !update) {
I suggest getting rid of `update` and refreshing this list every time component mounts. If it will affect the performance, will consider changing it.

2020-01-07 21:05 UTC, asketonim commented
Take a look and let me know what you think. Do we need to make this primitive registration as a separate component **now**?

2020-01-08 10:54 UTC, Eug-VS commented
@asketonim 
Haven't viewed your code yet, but this snippet can help you:
```
<TextField variant="outlined" id="username" label="Username" />
<Button
  variant="contained"
  color="secondary"
  size="large"
  style={{marginTop: '20px'}}
>
  Submit
</Button>
```
![image](https://user-images.githubusercontent.com/51545008/71972525-de1b6880-321d-11ea-9c68-bbcff481ce03.png)

More info: 
https://material-ui.com/components/text-fields/
https://material-ui.com/components/buttons/

P.S: Please, mark appropriate conversations as resolved after you resolve them.
P.P.S: You can use **re-request review** so I get notificated about it.

2020-01-08 16:18 UTC, eug-vs requested changes

2020-01-08 16:18 UTC, eug-vs commented on src/components/Profile/Profile.js
> +    post('users/', {username: user.username})
We can use ` post('users/', user)`, since it *literally* expands to `post('users/', { username: user.username, id: user.id })`. From the back-end perspective, it just **ignores** the `id` field you pass, so it would not harm existing logic.

After we get a response, simply `setUser(response.data)`.

2020-01-08 16:18 UTC, eug-vs commented on src/components/Profile/Profile.js
> +          setTimeout(() => {
Here you can already use the same logic as in #31

2020-01-08 16:18 UTC, eug-vs commented on src/components/Profile/Profile.js
> +console.log(user);
Please, remove. Commits should not contain any debugging code, unless it's the main purpose of commit.

2020-01-08 16:18 UTC, eug-vs commented on src/components/TimerPage/TimerPage.js
> +  // };
Feel free to remove this code. It was designed specifically for this reason: to mimic `user` prop that you will eventually pass to this component :)

2020-01-08 16:19 UTC, Eug-VS commented
@asketonim, yes, it would be nice to have registration as a separate component inside of `src/components/Profile/`

2020-01-12 15:14 UTC, Eug-VS commented
Close this PR due to unresolved conflicts and too long downtime.
More fresh version available: https://github.com/Eug-VS/chrono-cube/pull/35

2020-01-12 15:14 UTC, closed without merging